### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by lundmikkel** [chadly/Geocoding.net#104]

**Comment by chadly** [comment]
This was a triumph
I'm making a note here:
Huge success
It's hard to overstate
My satisfaction
Aperture Science
We do what we must
Because we can
For the good of all of us
Except the ones who are dead
But there's no sense crying
Over every mistake
You just keep on trying
Till you run out of cake
And the Science gets done
And you make a neat gun
For the people who are
Still alive

I'm not even angry
I'm being so sincere right now
Even though you broke my heart
And killed me
And tore me to pieces
And threw every piece into a fire
As they burned it hurt because
I was so happy for you!
Now these points of data
Make a beautiful line
And we're out of beta
We're releasing on time
So I'm glad. I got burned
Think of all the things we learned
For the people who are
Still alive

**Comment by lundmikkel** [comment]
I'll take that as a ... yes?
